# Generated by Django 4.1.7 on 2023-03-11 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('dg_delete', 'dg can delete message')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_id', models.UUIDField(editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(related_name='room', related_query_name='room', to='chat.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rooms', related_query_name='my_rooms', to=settings.AUTH_USER_MODEL)),
                ('room_admin', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('del_room', 'dg can delete room'), ('edit_room', 'dg can edit message'), ('access_room', 'dg access edit message'), ('make_admin', 'dg can make admin'), ('remove_member', 'dg can remove member'), ('dg_requests', 'dg can manage requests')],
            },
        ),
    ]
