# Generated by Django 4.1.7 on 2023-03-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('del_room', 'dg can delete room'), ('edit_room', 'dg can edit room'), ('access_room', 'dg access room'), ('make_admin', 'dg can make admin'), ('remove_member', 'dg can remove member'), ('dg_requests', 'dg can manage requests')]},
        ),
    ]
