# Generated by Django 4.1.7 on 2023-03-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('g_del_room', 'g can delete room'), ('g_edit_room', 'g can edit room'), ('g_access_room', 'g access room'), ('g_make_admin', 'g can make admin'), ('g_remove_member', 'g can remove member'), ('g_requests', 'g can manage requests'), ('g_del_msg', 'g delete messages')]},
        ),
    ]
