# Generated by Django 4.1.7 on 2023-03-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_room_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'permissions': [('super_admin', 'has super permisson over room')]},
        ),
    ]
