# Generated by Django 4.1.7 on 2023-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_anon',
            field=models.BooleanField(default=False),
        ),
    ]
