# Generated by Django 4.1.7 on 2023-03-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_room_messages_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='room', related_query_name='room', to='chat.message'),
        ),
    ]
