# Generated by Django 4.1.7 on 2023-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_message_options_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
